import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import CartProvider from "./CartProvider";
import { AuthProvider } from "./Provider";
import UserProvider from "./UserProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <UserProvider>
        <CartProvider>
        <Header/>
        {children}
        </CartProvider>
        </UserProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
